const GOOGLE_ADS_API_VERSION = 'v14';

const DATE_RANGES = {
  TODAY: 'TODAY',
  YESTERDAY: 'YESTERDAY',
  LAST_7_DAYS: 'LAST_7_DAYS',
  LAST_14_DAYS: 'LAST_14_DAYS',
  LAST_30_DAYS: 'LAST_30_DAYS',
  LAST_BUSINESS_WEEK: 'LAST_BUSINESS_WEEK',
  LAST_WEEK_SUN_SAT: 'LAST_WEEK_SUN_SAT',
  THIS_MONTH: 'THIS_MONTH',
  LAST_MONTH: 'LAST_MONTH'
};

const CAMPAIGN_STATUS = {
  ENABLED: 'ENABLED',
  PAUSED: 'PAUSED',
  REMOVED: 'REMOVED'
};

const CAMPAIGN_TYPES = {
  SEARCH: 'SEARCH',
  DISPLAY: 'DISPLAY',
  SHOPPING: 'SHOPPING',
  VIDEO: 'VIDEO',
  DISCOVERY: 'DISCOVERY',
  SMART: 'SMART',
  PERFORMANCE_MAX: 'PERFORMANCE_MAX'
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500
};

module.exports = {
  GOOGLE_ADS_API_VERSION,
  DATE_RANGES,
  CAMPAIGN_STATUS,
  CAMPAIGN_TYPES,
  HTTP_STATUS
};
